language: node_js
sudo: required
notifications:
  email: false
node_js:
- '10'
install:
  - npm ci
jobs:
  include:
  - stage: Lint
    script: npm run lint
  - stage: Test
    script: npm run test --coverage --maxWorkers=4 && npx codecov
  # - stage: Deploy
  #   script: npm run build && curl -sSL https://raw.githubusercontent.com/RedHatInsights/insights-frontend-builder-common/master/src/bootstrap.sh | bash -s
  - stage: Store
    script: ./deploy.sh
env:
    global:
    - REPO="git@github.com:RedHatInsights/xavier-ui-deploy"
    - REPO_DIR="xavier-ui-deploy"
    - BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    - NODE_OPTIONS="--max-old-space-size=4096 --max_old_space_size=4096"
